### ISSUE TITLE
feature request / bug - Adding sender iconUrl to loading animation

### ISSUE THREAD

**Issue by takumi-1** [line/line-bot-sdk-nodejs#1090]
I am using `sender` parameter [here](https://developers.line.biz/ja/docs/messaging-api/icon-nickname-switch/#customise-icon-and-display-name) to use custom icon for the LINE Official Account I have.

When I used [loading animation](https://developers.line.biz/ja/reference/messaging-api/#display-a-loading-indicator-request-body), it temporarily switches to the default icon, and switches back to the custom icon on message response.

It would be great if i could set the `sender` parameter in loading animation as well.

Thank you for your consideration.

**Comment by habara-k** [comment]
Thank you for using the Messaging API and line-bot-sdk-nodejs.

We appreciate your feedback. While this issue is not related to the SDK, we aim to support the customization of icons and nicknames with loading animations as part of the Messaging API.

We understand that prompt action may be challenging, and we kindly ask for your understanding. Thank you for your valuable input.
