### ISSUE TITLE
Receiving 429 error after migration to LINE Official Account

### ISSUE THREAD

**Issue by joseph1125** [line/line-bot-sdk-nodejs#159]
## Bug Report

**Describe the bug**
Since the migration, it is impossible to push message to a group chat

**To Reproduce**

1. Register a free account
2. Send push message to a LINE group
3. Returns 429 after a moment even it is well below the monthly limit

**Expected behavior**
I expect the message push to be working and receive 429 after I reach the limit

**Screenshots**
![image](https://user-images.githubusercontent.com/8279406/60851997-8d07c900-a228-11e9-8e9c-f64b86087df0.png)

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Node.js Version 12
 - line-bot-sdk-nodejs version(s) latest

**Additional context**
Since the migration, it seems that free accounts are not allowed to push message as it always returns 429 error even though the dashboard said that I'm well below the limit.

https://www.line-community.me/question/5cd4c845401690d976e7de92
https://www.line-community.me/question/5cf4e0d1401690d976e82834
https://www.line-community.me/question/5d0de8c4851f743fd7cd219e
https://www.line-community.me/question/5d0fb6c8851f743fd7cd24c8

**Comment by tkgauri** [comment]
Have you checked this?

https://developers.line.biz/en/reference/messaging-api/#send-push-message

**Comment by joseph1125** [comment]
Yes, I did, the same code was working when I was using developer trial

**Comment by tkgauri** [comment]
This might be due to the migration that we had recently(04/18)

https://developers.line.biz/en/docs/messaging-api/migrating-line-at/

As per the doc I shared in previous comments, it seems free plan accounts cannot call push message api.

Should you have further questions regarding plans/pricing please submit your query here:

**Comment by joseph1125** [comment]
Please understand that LINE@ account is already deprecated by your company and it is now migrated to LINE official account, this is a totally different plan

**Comment by joseph1125** [comment]
@tkgauri please reopen this issue since this issue definitely is not solved.

**Comment by tkgauri** [comment]
Hello @joseph1125 ,

429 is rate limit exceeded type of error.
Different rate limits apply depending upon your plan and country.
Thank for providing additional details about your plan.
However, this git repo issue is not the right place to handle plan related queries.
Hence, if you could please submit your question here: https://www.linebiz.com/jp-en/ it would be great.

After confirming the rate limits, if you’re sure that you’re not exceeding the limits applying to your plan and region and still getting 429, please submit the issue here and we would be happy to help.

Thanks!

**Comment by joseph1125** [comment]
yes, I'm way under the limit of the pushMessages, I only consume 3xx messages now

**Comment by xingoxu** [comment]
@joseph1125 
Since this problem is not related with sdk, I removed the `bug` tag.
Did you resolved your problem or there is still a problem ?
For Taiwan, you can post your question to here if you a confused with rating or plan at 
https://www.linebiz.com/tw/contact-us/
And it will be great if you ask them by providing the `request-id` and `bot id`.
