### ISSUE TITLE
Https request instead of http request

### ISSUE THREAD

**Issue by AliAyub007** [line/line-bot-sdk-nodejs#3]
There is http request in echo bot and line need https request. 
so how to convert this http to https? 

```javascript
app.post('/webhook', line.middleware(config), (req, res) => {
  Promise
    .all(req.body.events.map(handleEvent))
    .then((result) => res.json(result));
});
```

**Comment by be-hase** [comment]
Do you use Heroku ? https://github.com/line/line-bot-sdk-nodejs/issues/1
Heroku supports https protocol and offload(convert) it. 
You don't have to offload https to http.

```
LINE ---(https)---> Heroku ---(http)---> your app
```

If you don't use Heroku, Please refer to the below page.
http://expressjs.com/en/4x/api.html#app.listen

This issue is not related to SDK, so close it.
