### ISSUE TITLE
Error Code 401 when sending emoji message to bot

### ISSUE THREAD

**Issue by prakashdivyy** [line/line-bot-sdk-nodejs#46]
Hello LINE,

I'm using the code from the example to validating message from user.
But when I'm trying to send message which contains emoji, the webhook always return 401.

I have trying several changes in code for validating message but when sending emoji like this (🏁) the webhook still return 401.

Here is the code that I'm using right now, I'm using `jsesc` package to escape emoji

![image](https://user-images.githubusercontent.com/9023776/34474352-422e7432-efb0-11e7-9033-6c9cd722fe2f.png)

Thanks. 😄

**Comment by utatti** [comment]
Which example are you mentioning? It seems the code is not from this repository. You can simply use [`validateSignature()`](https://line.github.io/line-bot-sdk-nodejs/pages/api-reference/validate-signature.html) for validation. Is there any reason to implement it by yourself?

The problem itself is because `jsesc` converts the body into an ASCII-safe string, which can be completely different from the original (raw) body. The signature secret is computed from binary, so the best way in JS is using the raw `Buffer`. You can easily get the body as `Buffer` in Express or native `http` module.

Please ask me if anything's unclear. Thanks!

**Comment by prakashdivyy** [comment]
Thanks @utatti 😄

The problem itself is because express automatically parse `req.body` into JSON Object, not become a `Buffer`, so I have to make a new middleware before `bodyParser` to create `req.body` as `Buffer`.
