### ISSUE TITLE
[Question] : Why there are Unknown typings ?

### ISSUE THREAD

**Issue by wolffparkinson** [line/line-bot-sdk-nodejs#831]
Unknown types like `UnknownEvent`, `UnknownMessageContent` make it difficult to stay fully type safe, like how type safe previous SDK version was.

- Example : `event.type`  is loosely typed as `string` because `webhook.Event` has an `UnknownEvent` type in the union.

Q. Is this intentional ? 
Q. Could the API return other unknown event and the devs have to validate the events types like how its given in the example ?

`event.type === 'message' && event.message && event.message.type === 'text'`

It would be useful and Dx friendly if the OpenAPI codegen could provide stricter types.

**Comment by Yang-33** [comment]
Hi, thank you for using line-bot-sdk-nodejs, and nice questions, @wolffparkinson!

No, I don't believe it was intentional. Unlike other languages, the line-bot-sdk-nodejs directly handles JSON without the need for deserialization/serialization. In other languages(like Java), deserialization/serialization is necessary, which is why the unknown event needed to be defined. Undefined event from LINE will break applications if the fallback is defined. It's likely that the new code in line-bot-sdk-nodejs was influenced by this, but I don't think there was any intention behind it.

The main modification needed to remove it would involve deleting the following section. Are you interested in contributing?

https://github.com/line/line-bot-sdk-nodejs/blob/6b7e74fbd64b8d54779f76a3f3c5b780bfdd411c/generator/src/main/resources/line-bot-sdk-nodejs-generator/model.pebble#L18-L23

**Comment by wolffparkinson** [comment]
Yes definitely, i'd love to.

**Comment by Yang-33** [comment]
v9.2.1 removes `Unknown*` type.
release note: https://github.com/line/line-bot-sdk-nodejs/releases/tag/v9.2.1
